// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using FlowtideDotNet.AcceptanceTests.Entities;
using FlowtideDotNet.AcceptanceTests.Internal;
using FlowtideDotNet.Base.Engine;
using FlowtideDotNet.Base.Engine.Internal.StateMachine;
using FlowtideDotNet.Storage;
using FlowtideDotNet.Storage.Persistence;
using FlowtideDotNet.Storage.Persistence.Reservoir;
using FlowtideDotNet.Storage.Persistence.Reservoir.Internal;
using FlowtideDotNet.Storage.Persistence.Reservoir.MemoryDisk;
using FlowtideDotNet.Storage.StateManager.Internal;
using System;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using Xunit.Abstractions;

namespace FlowtideDotNet.AcceptanceTests
{
    // The StreamContext test hooks are process-wide statics, classes assigning them must not
    // run in parallel: one class's hook assignment or null-out clobbers the other's mid-test.
    [Collection("StreamContext test hooks")]
    public class CheckpointFailureTeardownTests : FlowtideAcceptanceBase
    {
        // The stream name generated by the harness contains the class name, the hooks
        // filter on it so tests running in parallel are not disturbed.
        private const string Token = "CheckpointFailureTeardownTests";

        public CheckpointFailureTeardownTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper, true)
        {
        }

        private sealed class FailingPageStorage : ReservoirPersistentStorage, IPersistentStorage
        {
            public int Armed;
            public readonly TaskCompletionSource<long> Failed = new(TaskCreationOptions.RunContinuationsAsynchronously);

            public FailingPageStorage() : base(new ReservoirStorageOptions { FileProvider = new MemoryFileProvider() })
            {
            }

            public new IPersistentStorageSession CreateSession() => new FailingPageSession(base.CreateSession(), this);

            private sealed class FailingPageSession(IPersistentStorageSession inner, FailingPageStorage storage) : IPersistentStorageSession
            {
                public bool SupportsConcurrentReads => inner.SupportsConcurrentReads;
                public Task Commit() => inner.Commit();
                public Task Delete(long key) => inner.Delete(key);
                public void Dispose() => inner.Dispose();
                public ValueTask<ReadOnlyMemory<byte>> Read(long key) => inner.Read(key);
                public ValueTask<T> Read<T>(long key, IStateSerializer<T> serializer) where T : ICacheObject => inner.Read(key, serializer);

                public Task Write(long key, SerializableObject value)
                {
                    // Fail actual page writes inside the background worker.
                    if (!value.HasPreSerializedData && Volatile.Read(ref storage.Armed) != 0 &&
                        new StackTrace().GetFrames().Any(frame =>
                            frame.GetMethod()?.DeclaringType?.Name.StartsWith("<CommitGenerationAsync>", StringComparison.Ordinal) == true) &&
                        Interlocked.Exchange(ref storage.Armed, 0) != 0)
                    {
                        storage.Failed.TrySetResult(storage.CurrentVersion - 1);
                        throw new CrashException("Injected background page write failure", new IOException("Page write failed"));
                    }
                    return inner.Write(key, value);
                }
            }
        }

        private sealed class FailingPageTestStream(string name) : FlowtideTestStream(name)
        {
            public FailingPageStorage Storage { get; } = new();

            protected override IPersistentStorage CreatePersistentStorage(string testName, bool ignoreSameDataCheck) => Storage;
        }

        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public async Task BackgroundPageWriteFailureRollsBackTheStreamAndAllowsFurtherCheckpoints(bool hasCompletedCheckpoint)
        {
            var name = $"{Token}_{nameof(BackgroundPageWriteFailureRollsBackTheStreamAndAllowsFurtherCheckpoints)}_{hasCompletedCheckpoint}";
            await using var stream = new FailingPageTestStream(name) { CachePageCount = 10000 };
            var restored = new TaskCompletionSource<long>(TaskCreationOptions.RunContinuationsAsynchronously);
            try
            {
                StreamContext.RestoreVersionForTests = (streamName, version) =>
                {
                    if (streamName == name) restored.TrySetResult(version);
                };
                stream.Generate(1000);
                if (!hasCompletedCheckpoint) Volatile.Write(ref stream.Storage.Armed, 1);
                await stream.StartStream("INSERT INTO output SELECT userkey, firstName FROM users", pageSize: 16);
                if (hasCompletedCheckpoint)
                {
                    await stream.WaitForUpdate().WaitAsync(TimeSpan.FromSeconds(30));
                    Volatile.Write(ref stream.Storage.Armed, 1);
                    stream.AddOrUpdateUser(new User { UserKey = 999999, FirstName = "failedcheckpoint" });
                }

                var deadline = DateTime.UtcNow.AddSeconds(30);
                while (!restored.Task.IsCompleted && DateTime.UtcNow < deadline)
                {
                    await stream.SchedulerTick();
                    await Task.Delay(10);
                }
                Assert.True(stream.Storage.Failed.Task.IsCompletedSuccessfully, "No background page write failed.");
                Assert.True(restored.Task.IsCompletedSuccessfully, "The stream did not initiate rollback.");
                var lastCompletedVersion = await stream.Storage.Failed.Task;
                Assert.Equal(lastCompletedVersion, await restored.Task);
                Assert.Equal(hasCompletedCheckpoint, lastCompletedVersion > 0);

                // Engine recovery discards failed session writes before replay.
                await stream.WaitForUpdate().WaitAsync(TimeSpan.FromSeconds(30));
                stream.AssertCurrentDataEqual(stream.Users.Select(user => new { user.UserKey, user.FirstName }));
                var recoveredVersion = stream.Storage.CurrentVersion;
                stream.AddOrUpdateUser(new User { UserKey = 999998, FirstName = "afterrecovery" });
                await stream.WaitForUpdate().WaitAsync(TimeSpan.FromSeconds(30));
                stream.AssertCurrentDataEqual(stream.Users.Select(user => new { user.UserKey, user.FirstName }));
                Assert.True(stream.Storage.CurrentVersion > recoveredVersion);
                Assert.Equal(1, stream.FailureNotificationCount);
            }
            finally
            {
                Volatile.Write(ref stream.Storage.Armed, 0);
                StreamContext.RestoreVersionForTests = null;
            }
        }

        /// <summary>
        /// A failure that lands while a checkpoint is committing must not let the failure
        /// teardown fault and dispose the blocks while the state manager is still being
        /// written, disposing during a state manager write corrupts it.
        /// </summary>
        [Fact]
        public async Task FailureTeardownWaitsForInFlightCheckpointCommit()
        {
            int writeInFlight = 0;
            bool disposedDuringWrite = false;
            var writeStarted = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var release = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var disposeObserved = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

            try
            {
                GenerateData();
                await StartStream("INSERT INTO output SELECT userkey, firstName FROM users");
                await WaitForUpdate();

                // Arm the hooks only after the initial checkpoint, holding the first one
                // would deadlock the initial update the stream startup waits for.
                StreamContext.CheckpointCommitHookForTests = async (streamName, lastVersion) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    Interlocked.Exchange(ref writeInFlight, 1);
                    writeStarted.TrySetResult();
                    await release.Task;
                    Interlocked.Exchange(ref writeInFlight, 0);
                };
                StreamContext.BeforeFailureDisposeForTests = (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    if (Volatile.Read(ref writeInFlight) == 1)
                    {
                        disposedDuringWrite = true;
                    }
                    disposeObserved.TrySetResult();
                };

                // Trigger a new checkpoint whose commit blocks on the hook.
                AddOrUpdateUser(new User() { UserKey = 999999, FirstName = "hooktrigger" });

                // Drive the scheduler until a checkpoint commit is held mid-write.
                var deadline = DateTime.UtcNow.AddSeconds(30);
                while (!writeStarted.Task.IsCompleted && DateTime.UtcNow < deadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }
                Assert.True(writeStarted.Task.IsCompleted, "No checkpoint commit was held by the hook");

                // Crash the stream while the commit is held, driving the failure teardown.
                await FireCrashTrigger();
                var failDeadline = DateTime.UtcNow.AddSeconds(15);
                while (State != StreamStateValue.Failure && State != StreamStateValue.NotStarted && DateTime.UtcNow < failDeadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }

                // Give the unfixed teardown a moment to reach the dispose point while the
                // commit is still held.
                await Task.Delay(500);

                // Release the held commit, the teardown may now proceed safely.
                release.TrySetResult();

                var observed = await Task.WhenAny(disposeObserved.Task, Task.Delay(TimeSpan.FromSeconds(30)));
                Assert.True(observed == disposeObserved.Task, "The failure teardown never reached the dispose point");

                Assert.False(disposedDuringWrite, "The failure teardown disposed the blocks while a checkpoint commit was still writing the state manager");
            }
            finally
            {
                release.TrySetResult();
                StreamContext.CheckpointCommitHookForTests = null;
                StreamContext.BeforeFailureDisposeForTests = null;
            }
        }

        /// <summary>
        /// A checkpoint that completes while the stream is failing is a valid, more recent
        /// recovery point, it captured a consistent snapshot at the barrier before the
        /// crash. The failure must roll back to that completed checkpoint, not discard it
        /// and roll back to the previous one.
        /// </summary>
        [Fact]
        public async Task FailureKeepsACheckpointThatCompletesDuringTeardown()
        {
            int writeInFlight = 0;
            long preCommitVersion = -1;
            long restoreVersion = -2;
            var writeStarted = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var release = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var restoreObserved = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

            try
            {
                GenerateData();
                await StartStream("INSERT INTO output SELECT userkey, firstName FROM users");
                await WaitForUpdate();

                StreamContext.CheckpointCommitHookForTests = async (streamName, lastVersion) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    // The last completed version before this commit, the commit in flight
                    // will produce the next one.
                    Interlocked.Exchange(ref preCommitVersion, lastVersion);
                    Interlocked.Exchange(ref writeInFlight, 1);
                    writeStarted.TrySetResult();
                    await release.Task;
                    Interlocked.Exchange(ref writeInFlight, 0);
                };
                StreamContext.RestoreVersionForTests = (streamName, version) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    Interlocked.Exchange(ref restoreVersion, version);
                    restoreObserved.TrySetResult();
                };

                AddOrUpdateUser(new User() { UserKey = 999998, FirstName = "keepcommit" });

                var deadline = DateTime.UtcNow.AddSeconds(30);
                while (!writeStarted.Task.IsCompleted && DateTime.UtcNow < deadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }
                Assert.True(writeStarted.Task.IsCompleted, "No checkpoint commit was held by the hook");

                await FireCrashTrigger();
                var failDeadline = DateTime.UtcNow.AddSeconds(15);
                while (State != StreamStateValue.Failure && State != StreamStateValue.NotStarted && DateTime.UtcNow < failDeadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }

                // Let the held commit finish, advancing the completed version past the one
                // that existed before it.
                release.TrySetResult();

                var observed = await Task.WhenAny(restoreObserved.Task, Task.Delay(TimeSpan.FromSeconds(30)));
                Assert.True(observed == restoreObserved.Task, "The failure teardown never determined a restore version");

                Assert.True(
                    Volatile.Read(ref restoreVersion) > Volatile.Read(ref preCommitVersion),
                    $"The failure rolled back to {Volatile.Read(ref restoreVersion)}, discarding the checkpoint that completed during the teardown (version after {Volatile.Read(ref preCommitVersion)})");
            }
            finally
            {
                release.TrySetResult();
                StreamContext.CheckpointCommitHookForTests = null;
                StreamContext.RestoreVersionForTests = null;
            }
        }

        /// <summary>
        /// The compaction that runs after a checkpoint also writes the state manager. A
        /// failure that lands while it is running must not let the teardown dispose the
        /// blocks or the state manager mid-write, the same hazard as the checkpoint commit.
        /// </summary>
        [Fact]
        public async Task FailureTeardownWaitsForInFlightCompaction()
        {
            int writeInFlight = 0;
            bool disposedDuringWrite = false;
            var writeStarted = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var release = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var disposeObserved = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

            try
            {
                GenerateData();
                await StartStream("INSERT INTO output SELECT userkey, firstName FROM users");
                await WaitForUpdate();

                StreamContext.CompactionHookForTests = async (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    Interlocked.Exchange(ref writeInFlight, 1);
                    writeStarted.TrySetResult();
                    await release.Task;
                    Interlocked.Exchange(ref writeInFlight, 0);
                };
                StreamContext.BeforeFailureDisposeForTests = (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    if (Volatile.Read(ref writeInFlight) == 1)
                    {
                        disposedDuringWrite = true;
                    }
                    disposeObserved.TrySetResult();
                };

                // Trigger a new checkpoint whose compaction blocks on the hook.
                AddOrUpdateUser(new User() { UserKey = 999997, FirstName = "compactiontrigger" });

                var deadline = DateTime.UtcNow.AddSeconds(30);
                while (!writeStarted.Task.IsCompleted && DateTime.UtcNow < deadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }
                Assert.True(writeStarted.Task.IsCompleted, "No compaction was held by the hook");

                await FireCrashTrigger();
                var failDeadline = DateTime.UtcNow.AddSeconds(15);
                while (State != StreamStateValue.Failure && State != StreamStateValue.NotStarted && DateTime.UtcNow < failDeadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }

                await Task.Delay(500);
                release.TrySetResult();

                var observed = await Task.WhenAny(disposeObserved.Task, Task.Delay(TimeSpan.FromSeconds(30)));
                Assert.True(observed == disposeObserved.Task, "The failure teardown never reached the dispose point");

                Assert.False(disposedDuringWrite, "The failure teardown disposed the blocks while a compaction was still writing the state manager");
            }
            finally
            {
                release.TrySetResult();
                StreamContext.CompactionHookForTests = null;
                StreamContext.BeforeFailureDisposeForTests = null;
            }
        }

        /// <summary>
        /// A compaction is decided and scheduled under the checkpoint lock, but runs later as a
        /// thread pool task. A failure that lands in that scheduling gap must still be waited
        /// for by the teardown: if the teardown's write-wait only sees writes that already
        /// started, it observes zero, disposes the blocks and the state manager, and the queued
        /// compaction then runs against the torn-down state - the same corruption the write
        /// wait exists to prevent, one scheduling hop earlier.
        /// </summary>
        [Fact]
        public async Task FailureTeardownWaitsForScheduledButNotStartedCompaction()
        {
            int pendingInGap = 0;
            bool disposedWhilePending = false;
            var gapEntered = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var release = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var disposeObserved = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

            try
            {
                GenerateData();
                await StartStream("INSERT INTO output SELECT userkey, firstName FROM users");
                await WaitForUpdate();

                // Holds the scheduled compaction task in the gap before it starts its work,
                // modelling a thread pool queueing delay.
                StreamContext.CompactionScheduledHookForTests = async (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    Interlocked.Exchange(ref pendingInGap, 1);
                    gapEntered.TrySetResult();
                    await release.Task;
                    Interlocked.Exchange(ref pendingInGap, 0);
                };
                StreamContext.BeforeFailureDisposeForTests = (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    if (Volatile.Read(ref pendingInGap) == 1)
                    {
                        disposedWhilePending = true;
                    }
                    disposeObserved.TrySetResult();
                };

                // Trigger a new checkpoint whose compaction gets scheduled and then parked in
                // the gap.
                AddOrUpdateUser(new User() { UserKey = 999996, FirstName = "gaptrigger" });

                var deadline = DateTime.UtcNow.AddSeconds(30);
                while (!gapEntered.Task.IsCompleted && DateTime.UtcNow < deadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }
                Assert.True(gapEntered.Task.IsCompleted, "No compaction task was held in the scheduling gap by the hook");

                // Crash the stream while the compaction is scheduled but has not started.
                await FireCrashTrigger();
                var failDeadline = DateTime.UtcNow.AddSeconds(15);
                while (State != StreamStateValue.Failure && State != StreamStateValue.NotStarted && DateTime.UtcNow < failDeadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }

                // Give the unfixed teardown a moment to reach the dispose point while the
                // compaction is still parked in the gap.
                await Task.Delay(500);

                // Release the parked compaction, the teardown may now proceed safely.
                release.TrySetResult();

                var observed = await Task.WhenAny(disposeObserved.Task, Task.Delay(TimeSpan.FromSeconds(30)));
                Assert.True(observed == disposeObserved.Task, "The failure teardown never reached the dispose point");

                Assert.False(disposedWhilePending, "The failure teardown disposed the blocks while a compaction was scheduled but had not yet started - the queued compaction would run against the disposed state manager");
            }
            finally
            {
                release.TrySetResult();
                StreamContext.CompactionScheduledHookForTests = null;
                StreamContext.BeforeFailureDisposeForTests = null;
            }
        }

        /// <summary>
        /// The checkpoint commit has the same scheduling gap as the compaction: it is decided
        /// under the checkpoint lock when the last egress acknowledges the barrier, but runs
        /// later as a thread pool task. A failure landing in that gap must be waited for by
        /// the teardown, otherwise the queued commit writes the state manager the teardown
        /// disposed.
        /// </summary>
        [Fact]
        public async Task FailureTeardownWaitsForScheduledButNotStartedCheckpointCommit()
        {
            int pendingInGap = 0;
            bool disposedWhilePending = false;
            var gapEntered = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var release = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var disposeObserved = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

            try
            {
                GenerateData();
                await StartStream("INSERT INTO output SELECT userkey, firstName FROM users");
                await WaitForUpdate();

                // Holds the scheduled commit task in the gap before it starts its work,
                // modelling a thread pool queueing delay.
                StreamContext.CheckpointCommitScheduledHookForTests = async (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    Interlocked.Exchange(ref pendingInGap, 1);
                    gapEntered.TrySetResult();
                    await release.Task;
                    Interlocked.Exchange(ref pendingInGap, 0);
                };
                StreamContext.BeforeFailureDisposeForTests = (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    if (Volatile.Read(ref pendingInGap) == 1)
                    {
                        disposedWhilePending = true;
                    }
                    disposeObserved.TrySetResult();
                };

                // Trigger a new checkpoint whose commit gets scheduled and then parked in the gap.
                AddOrUpdateUser(new User() { UserKey = 999995, FirstName = "commitgaptrigger" });

                var deadline = DateTime.UtcNow.AddSeconds(30);
                while (!gapEntered.Task.IsCompleted && DateTime.UtcNow < deadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }
                Assert.True(gapEntered.Task.IsCompleted, "No checkpoint commit task was held in the scheduling gap by the hook");

                // Crash the stream while the commit is scheduled but has not started.
                await FireCrashTrigger();
                var failDeadline = DateTime.UtcNow.AddSeconds(15);
                while (State != StreamStateValue.Failure && State != StreamStateValue.NotStarted && DateTime.UtcNow < failDeadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }

                // Give the unfixed teardown a moment to reach the dispose point while the
                // commit is still parked in the gap.
                await Task.Delay(500);

                // Release the parked commit, the teardown may now proceed safely.
                release.TrySetResult();

                var observed = await Task.WhenAny(disposeObserved.Task, Task.Delay(TimeSpan.FromSeconds(30)));
                Assert.True(observed == disposeObserved.Task, "The failure teardown never reached the dispose point");

                Assert.False(disposedWhilePending, "The failure teardown disposed the blocks while a checkpoint commit was scheduled but had not yet started - the queued commit would write the disposed state manager");
            }
            finally
            {
                release.TrySetResult();
                StreamContext.CheckpointCommitScheduledHookForTests = null;
                StreamContext.BeforeFailureDisposeForTests = null;
            }
        }

        /// <summary>
        /// Stop failure teardown waits for the in-flight stop commit.
        /// </summary>
        [Fact]
        public async Task StopFailureTeardownWaitsForInFlightStopCheckpointCommit()
        {
            int writeInFlight = 0;
            bool disposedDuringWrite = false;
            var writeStarted = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var release = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var disposeObserved = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            Task? stopTask = null;
            Task? failureTask = null;

            try
            {
                GenerateData();
                await StartStream("INSERT INTO output SELECT userkey, firstName FROM users");
                await WaitForUpdate();

                // Armed after initial checkpoint, next commit is the stop cycle's.
                StreamContext.CheckpointCommitHookForTests = async (streamName, lastVersion) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    Interlocked.Exchange(ref writeInFlight, 1);
                    writeStarted.TrySetResult();
                    await release.Task;
                    Interlocked.Exchange(ref writeInFlight, 0);
                };
                StreamContext.BeforeFailureDisposeForTests = (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    if (Volatile.Read(ref writeInFlight) == 1)
                    {
                        disposedDuringWrite = true;
                    }
                    disposeObserved.TrySetResult();
                };

                // Start the stop; its drain checkpoint's commit parks in the hook.
                stopTask = StopStream();

                var deadline = DateTime.UtcNow.AddSeconds(30);
                while (!writeStarted.Task.IsCompleted && DateTime.UtcNow < deadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }
                Assert.True(writeStarted.Task.IsCompleted, "No stop checkpoint commit was held by the hook");

                // A block faults while the stop commit is writing, for example a peer
                // substream dying mid-drain. Not awaited yet: the teardown it drives must
                // wait for the held commit, which the test releases below.
                failureTask = InjectFailure(new InvalidOperationException("Simulated block failure during stop drain"));

                // Give the unfixed teardown a moment to reach the dispose point while the
                // commit is still held.
                await Task.Delay(500);

                release.TrySetResult();

                var observed = await Task.WhenAny(disposeObserved.Task, Task.Delay(TimeSpan.FromSeconds(30)));
                Assert.True(observed == disposeObserved.Task, "The stop failure teardown never reached the dispose point");

                Assert.False(disposedDuringWrite, "The stop failure teardown faulted and disposed the blocks while the stop checkpoint commit was still writing the state manager");
            }
            finally
            {
                release.TrySetResult();
                StreamContext.CheckpointCommitHookForTests = null;
                StreamContext.BeforeFailureDisposeForTests = null;
                if (failureTask != null)
                {
                    await Task.WhenAny(failureTask, Task.Delay(TimeSpan.FromSeconds(30)));
                }
                if (stopTask != null)
                {
                    await Task.WhenAny(stopTask, Task.Delay(TimeSpan.FromSeconds(30)));
                }
            }
        }

        /// <summary>
        /// The stop checkpoint commit is decided under the checkpoint lock but runs later as
        /// a thread pool task, the same scheduling gap as the running state's commit. A
        /// failure during the stop that lands in that gap must also be waited for, otherwise
        /// the queued stop commit writes the state manager StopAll disposed.
        /// </summary>
        [Fact]
        public async Task StopFailureTeardownWaitsForScheduledButNotStartedStopCheckpointCommit()
        {
            int pendingInGap = 0;
            bool disposedWhilePending = false;
            var gapEntered = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var release = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var disposeObserved = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            Task? stopTask = null;
            Task? failureTask = null;

            try
            {
                GenerateData();
                await StartStream("INSERT INTO output SELECT userkey, firstName FROM users");
                await WaitForUpdate();

                StreamContext.CheckpointCommitScheduledHookForTests = async (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    Interlocked.Exchange(ref pendingInGap, 1);
                    gapEntered.TrySetResult();
                    await release.Task;
                    Interlocked.Exchange(ref pendingInGap, 0);
                };
                StreamContext.BeforeFailureDisposeForTests = (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    if (Volatile.Read(ref pendingInGap) == 1)
                    {
                        disposedWhilePending = true;
                    }
                    disposeObserved.TrySetResult();
                };

                stopTask = StopStream();

                var deadline = DateTime.UtcNow.AddSeconds(30);
                while (!gapEntered.Task.IsCompleted && DateTime.UtcNow < deadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }
                Assert.True(gapEntered.Task.IsCompleted, "No stop checkpoint commit task was held in the scheduling gap by the hook");

                failureTask = InjectFailure(new InvalidOperationException("Simulated block failure during stop drain"));

                await Task.Delay(500);

                release.TrySetResult();

                var observed = await Task.WhenAny(disposeObserved.Task, Task.Delay(TimeSpan.FromSeconds(30)));
                Assert.True(observed == disposeObserved.Task, "The stop failure teardown never reached the dispose point");

                Assert.False(disposedWhilePending, "The stop failure teardown faulted and disposed the blocks while the stop checkpoint commit was scheduled but had not yet started");
            }
            finally
            {
                release.TrySetResult();
                StreamContext.CheckpointCommitScheduledHookForTests = null;
                StreamContext.BeforeFailureDisposeForTests = null;
                if (failureTask != null)
                {
                    await Task.WhenAny(failureTask, Task.Delay(TimeSpan.FromSeconds(30)));
                }
                if (stopTask != null)
                {
                    await Task.WhenAny(stopTask, Task.Delay(TimeSpan.FromSeconds(30)));
                }
            }
        }
    }
}
