// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using FlowtideDotNet.AcceptanceTests.Entities;
using FlowtideDotNet.Base.Engine;
using FlowtideDotNet.Base.Engine.Internal.StateMachine;
using System;
using System.Threading;
using System.Threading.Tasks;
using Xunit.Abstractions;

namespace FlowtideDotNet.AcceptanceTests
{
    public class CheckpointFailureTeardownTests : FlowtideAcceptanceBase
    {
        // The stream name generated by the harness contains the class name, the hooks
        // filter on it so tests running in parallel are not disturbed.
        private const string Token = "CheckpointFailureTeardownTests";

        public CheckpointFailureTeardownTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper, true)
        {
        }

        /// <summary>
        /// A failure that lands while a checkpoint is committing must not let the failure
        /// teardown fault and dispose the blocks while the state manager is still being
        /// written, disposing during a state manager write corrupts it.
        /// </summary>
        [Fact]
        public async Task FailureTeardownWaitsForInFlightCheckpointCommit()
        {
            int writeInFlight = 0;
            bool disposedDuringWrite = false;
            var writeStarted = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var release = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var disposeObserved = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

            try
            {
                GenerateData();
                await StartStream("INSERT INTO output SELECT userkey, firstName FROM users");
                await WaitForUpdate();

                // Arm the hooks only after the initial checkpoint, holding the first one
                // would deadlock the initial update the stream startup waits for.
                StreamContext.CheckpointCommitHookForTests = async (streamName, lastVersion) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    Interlocked.Exchange(ref writeInFlight, 1);
                    writeStarted.TrySetResult();
                    await release.Task;
                    Interlocked.Exchange(ref writeInFlight, 0);
                };
                StreamContext.BeforeFailureDisposeForTests = (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    if (Volatile.Read(ref writeInFlight) == 1)
                    {
                        disposedDuringWrite = true;
                    }
                    disposeObserved.TrySetResult();
                };

                // Trigger a new checkpoint whose commit blocks on the hook.
                AddOrUpdateUser(new User() { UserKey = 999999, FirstName = "hooktrigger" });

                // Drive the scheduler until a checkpoint commit is held mid-write.
                var deadline = DateTime.UtcNow.AddSeconds(30);
                while (!writeStarted.Task.IsCompleted && DateTime.UtcNow < deadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }
                Assert.True(writeStarted.Task.IsCompleted, "No checkpoint commit was held by the hook");

                // Crash the stream while the commit is held, driving the failure teardown.
                await FireCrashTrigger();
                var failDeadline = DateTime.UtcNow.AddSeconds(15);
                while (State != StreamStateValue.Failure && State != StreamStateValue.NotStarted && DateTime.UtcNow < failDeadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }

                // Give the unfixed teardown a moment to reach the dispose point while the
                // commit is still held.
                await Task.Delay(500);

                // Release the held commit, the teardown may now proceed safely.
                release.TrySetResult();

                var observed = await Task.WhenAny(disposeObserved.Task, Task.Delay(TimeSpan.FromSeconds(30)));
                Assert.True(observed == disposeObserved.Task, "The failure teardown never reached the dispose point");

                Assert.False(disposedDuringWrite, "The failure teardown disposed the blocks while a checkpoint commit was still writing the state manager");
            }
            finally
            {
                release.TrySetResult();
                StreamContext.CheckpointCommitHookForTests = null;
                StreamContext.BeforeFailureDisposeForTests = null;
            }
        }

        /// <summary>
        /// A checkpoint that completes while the stream is failing is a valid, more recent
        /// recovery point, it captured a consistent snapshot at the barrier before the
        /// crash. The failure must roll back to that completed checkpoint, not discard it
        /// and roll back to the previous one.
        /// </summary>
        [Fact]
        public async Task FailureKeepsACheckpointThatCompletesDuringTeardown()
        {
            int writeInFlight = 0;
            long preCommitVersion = -1;
            long restoreVersion = -2;
            var writeStarted = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var release = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var restoreObserved = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

            try
            {
                GenerateData();
                await StartStream("INSERT INTO output SELECT userkey, firstName FROM users");
                await WaitForUpdate();

                StreamContext.CheckpointCommitHookForTests = async (streamName, lastVersion) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    // The last completed version before this commit, the commit in flight
                    // will produce the next one.
                    Interlocked.Exchange(ref preCommitVersion, lastVersion);
                    Interlocked.Exchange(ref writeInFlight, 1);
                    writeStarted.TrySetResult();
                    await release.Task;
                    Interlocked.Exchange(ref writeInFlight, 0);
                };
                StreamContext.RestoreVersionForTests = (streamName, version) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    Interlocked.Exchange(ref restoreVersion, version);
                    restoreObserved.TrySetResult();
                };

                AddOrUpdateUser(new User() { UserKey = 999998, FirstName = "keepcommit" });

                var deadline = DateTime.UtcNow.AddSeconds(30);
                while (!writeStarted.Task.IsCompleted && DateTime.UtcNow < deadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }
                Assert.True(writeStarted.Task.IsCompleted, "No checkpoint commit was held by the hook");

                await FireCrashTrigger();
                var failDeadline = DateTime.UtcNow.AddSeconds(15);
                while (State != StreamStateValue.Failure && State != StreamStateValue.NotStarted && DateTime.UtcNow < failDeadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }

                // Let the held commit finish, advancing the completed version past the one
                // that existed before it.
                release.TrySetResult();

                var observed = await Task.WhenAny(restoreObserved.Task, Task.Delay(TimeSpan.FromSeconds(30)));
                Assert.True(observed == restoreObserved.Task, "The failure teardown never determined a restore version");

                Assert.True(
                    Volatile.Read(ref restoreVersion) > Volatile.Read(ref preCommitVersion),
                    $"The failure rolled back to {Volatile.Read(ref restoreVersion)}, discarding the checkpoint that completed during the teardown (version after {Volatile.Read(ref preCommitVersion)})");
            }
            finally
            {
                release.TrySetResult();
                StreamContext.CheckpointCommitHookForTests = null;
                StreamContext.RestoreVersionForTests = null;
            }
        }

        /// <summary>
        /// The compaction that runs after a checkpoint also writes the state manager. A
        /// failure that lands while it is running must not let the teardown dispose the
        /// blocks or the state manager mid-write, the same hazard as the checkpoint commit.
        /// </summary>
        [Fact]
        public async Task FailureTeardownWaitsForInFlightCompaction()
        {
            int writeInFlight = 0;
            bool disposedDuringWrite = false;
            var writeStarted = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var release = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var disposeObserved = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

            try
            {
                GenerateData();
                await StartStream("INSERT INTO output SELECT userkey, firstName FROM users");
                await WaitForUpdate();

                StreamContext.CompactionHookForTests = async (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    Interlocked.Exchange(ref writeInFlight, 1);
                    writeStarted.TrySetResult();
                    await release.Task;
                    Interlocked.Exchange(ref writeInFlight, 0);
                };
                StreamContext.BeforeFailureDisposeForTests = (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    if (Volatile.Read(ref writeInFlight) == 1)
                    {
                        disposedDuringWrite = true;
                    }
                    disposeObserved.TrySetResult();
                };

                // Trigger a new checkpoint whose compaction blocks on the hook.
                AddOrUpdateUser(new User() { UserKey = 999997, FirstName = "compactiontrigger" });

                var deadline = DateTime.UtcNow.AddSeconds(30);
                while (!writeStarted.Task.IsCompleted && DateTime.UtcNow < deadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }
                Assert.True(writeStarted.Task.IsCompleted, "No compaction was held by the hook");

                await FireCrashTrigger();
                var failDeadline = DateTime.UtcNow.AddSeconds(15);
                while (State != StreamStateValue.Failure && State != StreamStateValue.NotStarted && DateTime.UtcNow < failDeadline)
                {
                    await SchedulerTick();
                    await Task.Delay(10);
                }

                await Task.Delay(500);
                release.TrySetResult();

                var observed = await Task.WhenAny(disposeObserved.Task, Task.Delay(TimeSpan.FromSeconds(30)));
                Assert.True(observed == disposeObserved.Task, "The failure teardown never reached the dispose point");

                Assert.False(disposedDuringWrite, "The failure teardown disposed the blocks while a compaction was still writing the state manager");
            }
            finally
            {
                release.TrySetResult();
                StreamContext.CompactionHookForTests = null;
                StreamContext.BeforeFailureDisposeForTests = null;
            }
        }
    }
}
