// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using FlowtideDotNet.Base;
using FlowtideDotNet.Base.Engine;
using FlowtideDotNet.Base.Engine.Internal.StateMachine;
using Xunit.Abstractions;

namespace FlowtideDotNet.AcceptanceTests
{
    public class StartupCheckpointAckTests : FlowtideAcceptanceBase
    {
        // The stream name generated by the harness contains the class name, the hook filters
        // on it so tests running in parallel are not disturbed.
        private const string Token = "StartupCheckpointAckTests";

        public StartupCheckpointAckTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
        }

        /// <summary>
        /// A checkpoint that was in flight when the stream failed can have its acknowledgement
        /// delivered late: a parallel egress fires its checkpoint done from an unconditional
        /// continuation, which can run after the failure teardown and after the stream has
        /// restarted back into the starting phase. That acknowledgement carries a real
        /// checkpoint event and lands in the starting state's EgressCheckpointDone. It must be
        /// ignored - during startup the only acknowledgement that state tracks is its own init
        /// watermarks event. Before the fix the init tracking set is not created until later in
        /// startup, so the acknowledgement dereferenced a null set (a release build NREs, the
        /// assert is stripped), and a set that already existed would be corrupted, dropping an
        /// egress from the init tracking before its real init watermarks event was handled and
        /// transitioning to running before watermark initialization completed.
        /// </summary>
        [Fact]
        public async Task StaleCheckpointAckDuringStartupIsIgnoredAndStartupCompletes()
        {
            var hookEntered = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var release = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            Task? startTask = null;

            try
            {
                StreamContext.StartupBeforeInitTrackingHookForTests = async (streamName) =>
                {
                    if (!streamName.Contains(Token))
                    {
                        return;
                    }
                    hookEntered.TrySetResult();
                    await release.Task;
                };

                GenerateData();
                // Not awaited: the start blocks in the hook until released, the stream is held
                // in the starting phase in the meantime.
                startTask = StartStream("INSERT INTO output SELECT userkey, firstName FROM users");

                var entered = await Task.WhenAny(hookEntered.Task, Task.Delay(TimeSpan.FromSeconds(30)));
                Assert.True(entered == hookEntered.Task, "The startup was never held before the init tracking was set up");
                Assert.Equal(StreamStateValue.Starting, State);

                // Deliver the stale checkpoint acknowledgement into the held starting phase. It
                // must be ignored rather than throw or disturb the init tracking.
                var thrown = Record.Exception(() => InjectEgressCheckpointDone("some_egress", new Checkpoint(1, 2)));
                Assert.Null(thrown);

                release.TrySetResult();
                await startTask;

                // Startup still completes cleanly and the stream reaches running and processes data.
                await WaitForUpdate();
                Assert.Equal(StreamStateValue.Running, State);
            }
            finally
            {
                release.TrySetResult();
                StreamContext.StartupBeforeInitTrackingHookForTests = null;
                if (startTask != null)
                {
                    await Task.WhenAny(startTask, Task.Delay(TimeSpan.FromSeconds(30)));
                }
            }
        }
    }
}
