// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using FlowtideDotNet.Base;
using FlowtideDotNet.Core.ColumnStore;
using FlowtideDotNet.Core.Utils;
using Microsoft.Extensions.Logging;
using FlowtideDotNet.Storage.DataStructures;
using FlowtideDotNet.Storage.Memory;
using FlowtideDotNet.Storage.Queue;
using FlowtideDotNet.Storage.StateManager;
using System.Diagnostics;

namespace FlowtideDotNet.Core.Operators.Exchange
{
    /// <summary>
    /// Exchange target that stores events for another substream.
    ///
    /// The queue is transient, its content is never part of a checkpoint. A checkpoint cycle
    /// in this stream only completes when the other substream has consumed the checkpoint
    /// barrier and sent its checkpoint done message, so everything in the queue is always
    /// ahead of the latest complete checkpoint. After a failure both substreams roll back to
    /// a common checkpoint and this stream regenerates the queue content by replaying from
    /// that checkpoint.
    /// </summary>
    internal class SubstreamTarget : IExchangeTarget
    {
        private readonly DataValueContainer _dataValueContainer;
        private readonly int _exchangeTargetId;
        private readonly int _columnCount;
        private readonly SubstreamCommunicationPoint _substreamCommunication;
        private readonly Action _targetCallDependenciesDone;
        private IFlowtideQueue<IStreamEvent, StreamEventValueContainer>? _queue;
        private IMemoryAllocator? _memoryAllocator;
        private readonly SemaphoreSlim _lockSemaphore;
        private Func<long, Task>? _failAndRecoverFunc;

        // False between a failure and the following initialize. The queue contents belong to
        // the aborted epoch until the state manager has rolled back and the stream regenerates
        // them, serving reads from them would deliver events from the old epoch.
        private bool _ready;

        // Set when this streams stop barrier has been stored in the queue, no more events are
        // stored after it. The stream may first finish stopping when the other substream has
        // fetched the stop barrier, otherwise the events before it would be disposed before
        // the other substream has received them.
        private volatile bool _stopBarrierStored;
        private volatile bool _stopBarrierFetched;

        private PrimitiveList<int>? _weights;
        private PrimitiveList<uint>? _iterations;
        private IColumn[]? _columns;

        public SubstreamTarget(
            int exchangeTargetId,
            int columnCount,
            SubstreamCommunicationPoint substreamCommunication,
            Action targetCallDependenciesDone)
        {
            this._exchangeTargetId = exchangeTargetId;
            _columnCount = columnCount;
            _substreamCommunication = substreamCommunication;
            this._targetCallDependenciesDone = targetCallDependenciesDone;
            _dataValueContainer = new DataValueContainer();
            _lockSemaphore = new SemaphoreSlim(1);
            _substreamCommunication.RegisterSubstreamTarget(_exchangeTargetId, this);
        }

        private void NewColumns()
        {
            Debug.Assert(_memoryAllocator != null);
            _columns = new IColumn[_columnCount];
            for (int i = 0; i < _columnCount; i++)
            {
                _columns[i] = Column.Create(_memoryAllocator);
            }

            _weights = new PrimitiveList<int>(_memoryAllocator);
            _iterations = new PrimitiveList<uint>(_memoryAllocator);
        }

        public Task AddCheckpointState(ExchangeOperatorState exchangeOperatorState)
        {
            // The queue is transient and is not saved with the checkpoint, its content is
            // regenerated by replay after a rollback.
            return Task.CompletedTask;
        }

        public ValueTask AddEvent(EventBatchWeighted weightedBatch, int index)
        {
            Debug.Assert(_columns != null);
            Debug.Assert(_weights != null);
            Debug.Assert(_iterations != null);

            _weights.Add(weightedBatch.Weights[index]);
            _iterations.Add(weightedBatch.Iterations[index]);

            for (int i = 0; i < _columns.Length; i++)
            {
                weightedBatch.EventBatchData.Columns[i].GetValueAt(index, _dataValueContainer, default);
                _columns[i].Add(_dataValueContainer);
            }
            return ValueTask.CompletedTask;
        }

        public async ValueTask BatchComplete(long time)
        {
            Debug.Assert(_weights != null);
            Debug.Assert(_iterations != null);
            Debug.Assert(_queue != null);
            Debug.Assert(_columns != null);

            if (_weights.Count > 0)
            {
                await _lockSemaphore.WaitAsync();
                try
                {
                    if (_stopBarrierStored)
                    {
                        // No events are stored after the stop barrier, the other substream
                        // unsubscribes when it consumes the barrier so a batch stored here
                        // would never be fetched. The rows are discarded, they are not part
                        // of any state committed before the barrier and are regenerated by
                        // replay at the next start.
                        foreach (var column in _columns)
                        {
                            column.Dispose();
                        }
                        _weights.Dispose();
                        _iterations.Dispose();
                        NewColumns();
                        return;
                    }
                    var msg = new StreamMessage<StreamEventBatch>(new StreamEventBatch(new EventBatchWeighted(_weights, _iterations, new EventBatchData(_columns))), time);
                    _substreamCommunication.Logger.SubstreamTargetStoresBatch(_exchangeTargetId);
                    await _queue.Enqueue(msg);
                    NewColumns();
                }
                finally
                {
                    _lockSemaphore.Release();
                }

                await _substreamCommunication.TargetHasData(_exchangeTargetId);
            }
        }

        public async Task Initialize(
            long restoreVersion,
            int targetId,
            IStateManagerClient stateManagerClient,
            ExchangeOperatorState state,
            IMemoryAllocator memoryAllocator,
            Func<long, Task> failAndRecoverFunc)
        {
            _failAndRecoverFunc = failAndRecoverFunc;
            _memoryAllocator = memoryAllocator;

            await _substreamCommunication.InitializeOperator(restoreVersion);

            _queue = await stateManagerClient.GetOrCreateQueue($"events_target_{targetId}", new FlowtideQueueOptions<IStreamEvent, StreamEventValueContainer>()
            {
                MemoryAllocator = memoryAllocator,
                ValueSerializer = new StreamEventValueSerializer(memoryAllocator)
            });

            NewColumns();

            await _lockSemaphore.WaitAsync();
            _ready = true;
            _stopBarrierStored = false;
            _stopBarrierFetched = false;
            _lockSemaphore.Release();
        }

        /// <summary>
        /// True when the other substream has fetched the stop barrier, or no stop barrier has
        /// been stored. The stream keeps running stop checkpoint cycles until the barrier has
        /// been fetched so the events before it reach the other substream before this stream
        /// disposes its queue.
        /// </summary>
        public bool ReadyToStop => !_stopBarrierStored || _stopBarrierFetched;

        public void NewBatch(EventBatchWeighted weightedBatch)
        {
        }

        public async Task OnLockingEvent(ILockingEvent lockingEvent)
        {
            Debug.Assert(_queue != null);
            // Logged before the semaphore so a barrier that reached the exchange but is
            // blocked behind an in progress read or write is distinguishable from a barrier
            // that never arrived.
            _substreamCommunication.Logger.LogDebug("Target {targetId} received locking event {eventType}", _exchangeTargetId, lockingEvent.GetType().Name);
            await _lockSemaphore.WaitAsync();
            try
            {
                if (_stopBarrierStored)
                {
                    // The stream is stopping and may run multiple stop checkpoint cycles while
                    // it drains, the other substream only needs the first stop barrier.
                    return;
                }
                _substreamCommunication.Logger.LogDebug("Target {targetId} stores locking event {eventType}", _exchangeTargetId, lockingEvent.GetType().Name);
                await _queue.Enqueue(lockingEvent);
                if (lockingEvent is StopStreamCheckpoint)
                {
                    _stopBarrierStored = true;
                }
            }
            finally
            {
                _lockSemaphore.Release();
            }
            await _substreamCommunication.TargetHasData(_exchangeTargetId);
        }

        public async Task OnLockingEventPrepare(LockingEventPrepare lockingEventPrepare)
        {
            Debug.Assert(_queue != null);
            await _lockSemaphore.WaitAsync();
            try
            {
                if (_stopBarrierStored)
                {
                    return;
                }
                await _queue.Enqueue(lockingEventPrepare);
            }
            finally
            {
                _lockSemaphore.Release();
            }
            await _substreamCommunication.TargetHasData(_exchangeTargetId);
        }

        public async Task OnWatermark(Watermark watermark)
        {
            Debug.Assert(_queue != null);
            await _lockSemaphore.WaitAsync();
            try
            {
                if (_stopBarrierStored)
                {
                    return;
                }
                await _queue.Enqueue(watermark);
            }
            finally
            {
                _lockSemaphore.Release();
            }
            await _substreamCommunication.TargetHasData(_exchangeTargetId);
        }

        /// <summary>
        /// Dequeues events for the other substream. The events are removed from the queue,
        /// they are always ahead of the latest complete checkpoint since a checkpoint only
        /// completes when the other substream has consumed its barrier, so after a failure
        /// both substreams roll back to a common checkpoint and the events are regenerated.
        /// </summary>
        public async ValueTask<bool> ReadData(List<SubstreamEventData> outputList, int maxCount)
        {
            // the target is not yet initialized
            if (_queue == null)
            {
                return false;
            }
            await _lockSemaphore.WaitAsync();
            try
            {
                if (!_ready)
                {
                    return false;
                }
                int count = 0;
                while (_queue.Count > 0 && count < maxCount)
                {
                    var val = await _queue.Dequeue();
                    // Dequeuing advances an index but the queue page still references the
                    // event and returns its rent when the page is disposed, so the event is
                    // rented again for the receiver.
                    StreamEventRent.Rent(val);
                    if (val is StopStreamCheckpoint)
                    {
                        // The other substream has now received everything up to and including
                        // the stop barrier, this stream can finish stopping.
                        _stopBarrierFetched = true;
                    }
                    outputList.Add(new SubstreamEventData()
                    {
                        ExchangeTargetId = _exchangeTargetId,
                        StreamEvent = val
                    });
                    count++;
                }
                return _queue.Count > 0;
            }
            finally
            {
                _lockSemaphore.Release();
            }
        }

        public async Task OnFailure(long recoveryPoint)
        {
            // Stop serving reads until the state has been rolled back and initialize has run,
            // waiting on the semaphore also drains a read that is currently in progress.
            await _lockSemaphore.WaitAsync();
            _ready = false;
            _lockSemaphore.Release();
            _substreamCommunication.OnStreamFailure();
            // Best effort notification that must not delay the failure handling here, see
            // NotifyFailAndRecover.
            _substreamCommunication.NotifyFailAndRecover(recoveryPoint);
        }

        public Task FailAndRecover(long recoveryPoint)
        {
            if (_failAndRecoverFunc == null)
            {
                // The stream has not initialized this target yet, there is no committed work
                // past the recovery point to roll back. The initialize handshake reconciles
                // the checkpoint versions when the stream starts.
                return Task.CompletedTask;
            }
            return _failAndRecoverFunc(recoveryPoint);
        }

        public Task TargetSubstreamCheckpointDone(long checkpointVersion)
        {
            _targetCallDependenciesDone();
            return Task.CompletedTask;
        }

        public Task CheckpointDone(long checkpointVersion)
        {
            return _substreamCommunication.SendCheckpointDone(checkpointVersion);
        }
    }
}
