services:
  stream:
    depends_on:
      sqlserver.configurator:
        condition: service_completed_successfully
    build: 
      context: ../../
      dockerfile: samples/SqlServerToOpenFga/Dockerfile
    environment:
      CUSTOMCONNSTR_SqlServer: "Server=sqlserver;Database=demo;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True"
    ports:
      - "8000:80"
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'yourStrong(!)Password' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./:/docker-entrypoint-initdb.d
    depends_on:
      sqlserver:
        condition: service_healthy
    command: "bash -c '/opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P \"yourStrong(!)Password\" -d master -i docker-entrypoint-initdb.d/bootstrap.sql'"
  openfga:
    image: "openfga/openfga"
    command: "run"
    ports:
    - "8080:8080"
    - "8081:8081"
    - "3000:3000" 
    