<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>$(DefaultNetTargetFramework)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>$(DefineConstants);MI_DEBUG</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FlowtideDotNet.MiMalloc.Tests" />
    <InternalsVisibleTo Include="FlowtideDotNet.Storage" />
  </ItemGroup>

</Project>
