// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using FlowtideDotNet.Core.Operators.Exchange;
using FlowtideDotNet.Cluster.Orleans.Messages;
using Orleans.Serialization.Buffers;
using Orleans.Serialization.Cloning;
using Orleans.Serialization.Codecs;
using Orleans.Serialization.WireProtocol;
using System.Buffers;

namespace FlowtideDotNet.Cluster.Orleans.Internal
{
    /// <summary>
    /// Serializes <see cref="SubstreamEventsPayload"/> only when a message actually crosses
    /// a silo boundary: Orleans invokes codecs at transport time, so grains on the same silo
    /// never pay for serialization. Writes the substream wire format (columnar, batch level)
    /// directly into the message and releases the events' receiver claims on the sending
    /// side; reading captures the raw payload into pooled segments without materializing the
    /// events, the communication handler deserializes lazily with the consuming operator's
    /// allocator.
    /// </summary>
    [RegisterSerializer]
    public sealed class SubstreamEventsPayloadCodec : IFieldCodec<SubstreamEventsPayload>
    {
        private static readonly Type CodecFieldType = typeof(SubstreamEventsPayload);
        private readonly SubstreamEventWireSerializer _wireSerializer = new SubstreamEventWireSerializer();

        public void WriteField<TBufferWriter>(ref Writer<TBufferWriter> writer, uint fieldIdDelta, Type expectedType, SubstreamEventsPayload value) where TBufferWriter : IBufferWriter<byte>
        {
            if (ReferenceCodec.TryWriteReferenceField(ref writer, fieldIdDelta, expectedType, value))
            {
                return;
            }
            writer.WriteFieldHeader(fieldIdDelta, expectedType, CodecFieldType, WireType.LengthPrefixed);

            // The wire format is written into a pooled buffer first, the length prefix
            // requires the size before the bytes.
            var buffer = new PooledBuffer();
            IBufferWriter<byte> bufferWriter = buffer;
            if (value.TryTakeLive(out var events))
            {
                try
                {
                    _wireSerializer.Serialize(events, bufferWriter);
                }
                catch
                {
                    ((PooledBuffer)bufferWriter).Dispose();
                    throw;
                }
                finally
                {
                    // The claims end on the sending side, the receiver deserializes fresh
                    // copies. Also released when serialization fails: the requestor sees the
                    // failed fetch and fails over, the events are regenerated by replay.
                    SubstreamEventWireSerializer.ReturnEvents(events);
                }
                WriteBuffer(ref writer, (PooledBuffer)bufferWriter);
            }
            else if (value.IsSerialized)
            {
                // A payload that already crossed a silo is forwarded as its raw bytes.
                ((PooledBuffer)bufferWriter).Dispose();
                WriteBuffer(ref writer, value.TakeSerialized());
            }
            else
            {
                throw new InvalidOperationException("The substream events payload was already consumed, a payload is bound to exactly one response.");
            }
        }

        private static void WriteBuffer<TBufferWriter>(ref Writer<TBufferWriter> writer, PooledBuffer buffer) where TBufferWriter : IBufferWriter<byte>
        {
            try
            {
                writer.WriteVarUInt32((uint)buffer.Length);
                foreach (var segment in buffer.AsReadOnlySequence())
                {
                    writer.Write(segment.Span);
                }
            }
            finally
            {
                buffer.Dispose();
            }
        }

        public SubstreamEventsPayload ReadValue<TInput>(ref Reader<TInput> reader, Field field)
        {
            if (field.IsReference)
            {
                return ReferenceCodec.ReadReference<SubstreamEventsPayload, TInput>(ref reader, field);
            }
            field.EnsureWireType(WireType.LengthPrefixed);

            var remaining = (int)reader.ReadVarUInt32();
            // Captured into pooled segments without materializing the events, the handler
            // deserializes lazily with the consuming operator's allocator.
            var buffer = new PooledBuffer();
            IBufferWriter<byte> bufferWriter = buffer;
            try
            {
                while (remaining > 0)
                {
                    var span = bufferWriter.GetSpan(Math.Min(remaining, 4096));
                    var toRead = Math.Min(span.Length, remaining);
                    reader.ReadBytes(span.Slice(0, toRead));
                    bufferWriter.Advance(toRead);
                    remaining -= toRead;
                }
            }
            catch
            {
                ((PooledBuffer)bufferWriter).Dispose();
                throw;
            }
            var result = new SubstreamEventsPayload((PooledBuffer)bufferWriter);
            ReferenceCodec.RecordObject(reader.Session, result);
            return result;
        }
    }

    /// <summary>
    /// The payload transfers ownership of the events with the reference; grains on the same
    /// silo hand the live events over uncopied. A deep copy would double the receiver claims.
    /// </summary>
    [RegisterCopier]
    public sealed class SubstreamEventsPayloadCopier : IDeepCopier<SubstreamEventsPayload>
    {
        public SubstreamEventsPayload DeepCopy(SubstreamEventsPayload input, CopyContext context)
        {
            return input;
        }
    }
}
